spring:
  #  数据库配置
  datasource:
    username: root
    password: Gqb2275237.
    #        password: 123456
    url: jdbc:mysql://124.222.27.22:3306/qingbing?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    #   下面的内容是额外配置，如果不需要直接删除就行 不用配
    #   换阿里的druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    #    配置druid
    druid:
      max-active: 20
      initial-size: 5
      min-idle: 10
      max-wait: 60000
  # servlet
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB
  #redis
  redis:
    host: 124.222.27.22
    port: 6371
    password: 2275237

  rabbitmq:
    host: junmooo.x3322.net
    port: 5672
    username: guest
    password: guest
    # 消息发送确认
    publisher-confirm-type: correlated
    # 开启发送失败退回
    publisher-returns: true
    listener:
      simple:
        # 消费端最小并发数
        concurrency: 1
        # 消费端最大并发数
        max-concurrency: 100
        # 一次请求中预处理的消息数量
        prefetch: 100
        # 手动应答
        acknowledge-mode: manual
        retry:
          ### 开启重试机制(调用监听方法失败时会重试，不是从队列中重复拿消息)
          enabled: true
          #最大重试传递次数
          max-attempts: 3
          #第一次和第二次尝试传递消息的间隔时间 单位毫秒
          initial-interval: 5000ms
          #最大重试时间间隔，单位毫秒
          max-interval: 300000ms
          #应用前一次重试间隔的乘法器，multiplier默认为1
          multiplier: 3
          #以上配置的间隔0s  5s  15s  45s

#配置日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# Prometheus的相关
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
#自定义变量
env:
  #    dir-path: "/Users/junmooo/files/"
  dir-path: "/root/home/files/imgs/"
  basket: "https://qingbing.top/imgs/"
  photo-dir-path: "/root/home/files/photo/"
  photo-basket: "https://qingbing.top/photo/"
  store-dir-path: "/root/home/files/store/"
  store-basket: "https://qingbing.top/store/"
  default-tree: "[{\"title\":\"READ ME\",\"key\":\"7166e51d-cc2f-4b01-9269-dfc74267fb28\"},{\"title\":\"MarkDown语法\",\"key\":\"07d6b466-38cc-4465-867a-63298e75d1ae\"}]"
server:
  port: 8089